### ISSUE TITLE
oapng2gif command does not execute the program [Windows CMD]

### ISSUE THREAD

**Issue by Mosencrantz** [hoyangtsai/all-apng2gif#2]
Nothing happens upon executing oapng2gif, files are still in .apng format
![image](https://user-images.githubusercontent.com/68965847/160255495-e08431a2-be51-412c-a3b5-724bdaadd8eb.png)
![image](https://user-images.githubusercontent.com/68965847/160255516-d6a79f0f-8d18-4044-b988-8f9759049d55.png)

**Comment by hoyangtsai** [comment]
Try to use [Windows Terminal](https://docs.microsoft.com/en-us/windows/terminal/).
The tool never tested on Windows, but Windows Terminal is a more unix-like shell application, it should be worked.
